server:
  port: 7771
  servlet:
    context-path: /blog
spring:
  datasource:
    url: jdbc:mysql://47.95.218.235:3306/blog?autoReconnect=true&characterEncoding=UTF-8
    username: root
    password: Passwd235
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
    mvc:
      static-path-pattern: /**
    resources:
      static-locations: classpath:/static/
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    suffix: .html
    servlet:
      content-type: text/html
      prefix: classpath:/templates
  redis:
    host: 47.95.218.235
    port: 6379
    password: Passwd235
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
      lettuce:
        shutdown-timeout: 0

mybatis:
  mapper-locations: classpath:mapper/*.xml
 # type-aliases-package: ***  实体扫描，多个package用逗号或者分号分隔 自己的实体类地址 
  configuration:
        # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  
 # 打印sql
#logging:
  #level:
    # com.tao.blog: debug
#pagehelper:
#   helperDialect:mysql
#   reasonable:true
#   supportMethodsArguments:true
#   pageSizeZero:true
#   params:count=countSql